excerpt_separator: <!--more-->

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

# --- 网站信息设置 ---
name: ZoeyWoohoo
title: ZoeyWoohoo's blog
description: Moving on and getting over!
url: https://zoeywoohoo.top/
copyright_time: 2023
# 标签页 logo url
# favicon: https://showzeng.itscoder.com/assets/img/shortcut_icon.webp
# 头像 url
# avatar: https://showzeng.itscoder.com/assets/img/avatar.webp
# --- 网站信息设置 ---


# --- 社交链接 ---
instagram: https://www.instagram.com/zoeywoohoo
github: https://www.github.com/zoeywoohoo
email: mailto:kingstageshow@gmail.com
rss: true
# --- 社交链接 ---


# --- 站点统计 ---
site_statistics: true
# cnzz (友盟统计)
cnzz_id: 1274412575
# Baidu (百度统计)
# baidu_id: f74c091a6d90f6f6fe77641d82db3443
# Google Analytics (谷歌统计)
google_id: G-WPNT71GZYB
# --- 站点统计 ---


# --- 版权声明 ---
# 禁止复制 (注：启用后仅文章页和关于页禁止复制)
# lock_copy: true
# 禁止右键菜单 (注：为全局设置，启用后所有页面均无法使用右键菜单)
lock_menu: true
# 复制文本末尾添加版权声明 (注：启用后仅文章页和关于页复制添加版权声明)
copy_with_declaration: true
# --- 版权声明 ---


# --- 打赏设置 ---
reward: false
reward_description: 如果你觉得本文对你有帮助，不妨请我喝瓶葡萄味芬达
wechat_qr: true
alipay_qr: true
# --- 打赏设置 ---


# --- 评论设置 ---
comment: false
# 来必力
livere_uid: MTAyMC8zODc0Ny8xNTI3NQ==
# gitment
# gitment_owner: showzeng
# gitment_repo: showzeng.github.io
# gitment_client_id: 76bb22ffd69cb9a2dc11
# gitment_secret: 1bc48766be80fbcb2802679ab796d76ac4fafe44
# --- 评论设置 ---

show_excerpt: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - new
